### ISSUE TITLE
Incorrect instructions to download the sample

### ISSUE THREAD

**Issue by ramical** [AzureADSamples/Daemon-DotNet#2]
This step to download the sample did not work:

Step 1: Clone or download this repository
From your shell or command line:

 git clone git@github.com:AzureADSamples/Daemon-DotNet.git 

I got this error:

D:\Projects\AADLibSamples> git clone git@github.com:AzureADSamples/Daemon-DotNet.git
Cloning into 'Daemon-DotNet'...
The authenticity of host 'github.com (192.30.252.128)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.128' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

The right step was:
git clone https://github.com/AzureADSamples/Daemon-DotNet

Thanks!

**Comment by CamronBute** [comment]
This is only a problem if you don't have SSH set up. Worked for me.

**Comment by dstrockis** [comment]
I think https is generally easier for most people - we updated the readme a while back. Thanks Camron
