### ISSUE TITLE
Authorization has been denied for this request

### ISSUE THREAD

**Issue by Compusa** [AzureADSamples/Daemon-DotNet#4]
After downloading the sample, we have tried to recreate this sample but we can't get it to work. We have double checked the configuration/steps needed for the client and the service, but still no success.

We have run the client in the debugger and we get a token when we call "AquireToken" on the AuthenticationContext. We get the following message when we call our service:
“Authorization has been denied for this request.”

We have tried anything that we can think of, with no success. Suggestions on how to solve/troubleshoot this problem, would be very much appreciated.

**Comment by dstrockis** [comment]
I would recommend triple checking your config values on both daemon and service.  If you want to capture a fiddler trace and mail it to me, I would be happy to take a quick look.

**Comment by lysaghtm** [comment]
I am also getting this error. I encountered the following 2 issues that may or may not be relevant

1) In the readme, it says replace the ids:ClientID key for the todoListService but the web.config does not contain such a key.
2) The Audience property in Startup.Auth is deprecated, the warning suggests using TokenValidationParameters.ValidAudience

Regards,
Michael Lysaght

**Comment by dstrockis** [comment]
Thanks Michael.  On #1 - That step is unnecessary. I've removed it from the README. Thanks for the catch . On #2 - You can ignore that warning.

I'm still not sure what is causing this error. I would double check that the Audience value in the service exactly matches the TodoListResourceId in the daemon.  If you want to mail me a trace of the token acquisition and failing API call, I would be happy to help diagnose.

**Comment by lysaghtm** [comment]
This is working now. I don't know what the initial problem was, I suspect an error on my part with one of the config settings. I completely started over from scratch and it works.
